### ISSUE TITLE
Compilation Issue With VS 2019

### ISSUE THREAD

**Issue by TrevorCash** [MADEAPPS/newton-dynamics#184] opened 2019-09-18 16:37 UTC
Hi Julio,

I upgraded to vs 2019 and tried compiling the demos-sandbox.  I am getting this error:

![image](https://user-images.githubusercontent.com/2559371/65167558-09c0db80-da00-11e9-8b5c-4d1dd4cf9b72.png)

**Comment by JulioJerez** [comment] 2019-09-18 17:08
that's a serious bug, no way the tread ID does no match the id of the caller thread onlease teh parameter threadData is wrong.

```
void* dgThread::dgThreadSystemCallback(void* threadData)
{
	dgFloatExceptions exception;
	dgSetPrecisionDouble precision;

	dgThread* const me = (dgThread*) threadData;
	D_SET_TRACK_NAME(me->m_name);
	me->Execute(me->m_id);
	dgInterlockedExchange(&me->m_threadRunning, 0);
	return 0;
}
```

I hope MS did add some shenanigan  to the thread callback user data object.
I do not have VS 2019, I will try tonight.
is this the free version?

**Comment by TrevorCash** [comment] 2019-09-18 17:10
Yeah I thought it was an odd bug to see a threading bug like this pop up.  yeah its the free (community) version

**Comment by JulioJerez** [comment] 2019-09-18 18:00
of topic, can you build on lower version of Visual studio? is so has you
seem the work on the robot manipulators.
I though you might be interested on that sort of thing? it is is all
Physics by the book.

**Comment by TrevorCash** [comment] 2019-09-18 18:56
yeah the reason I tried vs 2019 is because rbfx is starting to move to 2019 due to c++14 features.  yeah I want to check out the demos.  do the manipulators works with the standard joints?  yeah Robotics in tech game is what I want to move towards.

**Comment by JulioJerez** [comment] 2019-09-18 19:31
all plain and simple hinges yes, no more esoteric inverse IK  joints.
it does uses a listener which is encapsulate in a new library called dModel.
this new dModel library will superseded all the competitive that is in the
dCustomJoint and do no belong there.

the definition of a dModel in newton is a collection of of hiding bodies,
collision and joint wrapped under a listener.
they have a pre and post update the the client app can use to  apply
control to the model.

this will be the base call for vehicles and animated characters.
next I will refactor the hexapod and teh I will try to make eighth the TRed
of a AT-ST like robot, cross my finger knock on wood.

**Comment by TrevorCash** [comment] 2019-09-18 21:05
A single manager makes sense.  Ill have to try that out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TrevorCash** [comment] 2019-09-18 21:58
Just tried the SixAxisManipulator Demo - Super Cool

**Comment by DaveGravel** [comment] 2019-09-19 04:30
Hi TrevorCash, I know this is not the solution for the problem, But if you absolutly need to build newton for work on your project with 2019 you can uncomment //#define DG_USE_THREAD_EMULATION in dgTypes.h file.
On this way you can continue to work with your project from 2019 in waiting the real fix.

**Comment by TrevorCash** [comment] 2019-09-19 15:32
Hi Dave, Great!  Thanks for letting me know!

**Comment by DaveGravel** [comment] 2019-09-20 04:44
Hi TrevorCash.
If you try again with last sdk, 
You don't need to uncomment //#define DG_USE_THREAD_EMULATION anymore.
The problem is fixed with 2019 now. 
I have do some tests and it work good for me.

**Closed** 2019-09-20 19:29 UTC
